/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JwksDotjsonRouteImport } from './routes/jwks[.]json'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ClientMetadataDotjsonRouteImport } from './routes/client-metadata[.]json'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiVoteRouteImport } from './routes/api/vote'
import { Route as ApiTrendingRouteImport } from './routes/api/trending'
import { Route as ApiTagsRouteImport } from './routes/api/tags'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiQuestionsIndexRouteImport } from './routes/api/questions/index'
import { Route as QDidRkeyRouteImport } from './routes/q/$did/$rkey'
import { Route as ApiRecordsUriRouteImport } from './routes/api/records/$uri'
import { Route as ApiProfilesHandleRouteImport } from './routes/api/profiles/$handle'
import { Route as ApiAnalyticsViewRouteImport } from './routes/api/analytics/view'
import { Route as ApiAnalyticsShareRouteImport } from './routes/api/analytics/share'
import { Route as ApiQuestionsUriIndexRouteImport } from './routes/api/questions/$uri/index'
import { Route as ApiQuestionsUriAnswersRouteImport } from './routes/api/questions/$uri/answers'
import { Route as ApiQuestionsUriAcceptRouteImport } from './routes/api/questions/$uri/accept'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JwksDotjsonRoute = JwksDotjsonRouteImport.update({
  id: '/jwks.json',
  path: '/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMetadataDotjsonRoute = ClientMetadataDotjsonRouteImport.update({
  id: '/client-metadata.json',
  path: '/client-metadata.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteRoute = ApiVoteRouteImport.update({
  id: '/api/vote',
  path: '/api/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendingRoute = ApiTrendingRouteImport.update({
  id: '/api/trending',
  path: '/api/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsIndexRoute = ApiQuestionsIndexRouteImport.update({
  id: '/api/questions/',
  path: '/api/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QDidRkeyRoute = QDidRkeyRouteImport.update({
  id: '/q/$did/$rkey',
  path: '/q/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsUriRoute = ApiRecordsUriRouteImport.update({
  id: '/api/records/$uri',
  path: '/api/records/$uri',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesHandleRoute = ApiProfilesHandleRouteImport.update({
  id: '/api/profiles/$handle',
  path: '/api/profiles/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsViewRoute = ApiAnalyticsViewRouteImport.update({
  id: '/api/analytics/view',
  path: '/api/analytics/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsShareRoute = ApiAnalyticsShareRouteImport.update({
  id: '/api/analytics/share',
  path: '/api/analytics/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsUriIndexRoute = ApiQuestionsUriIndexRouteImport.update({
  id: '/api/questions/$uri/',
  path: '/api/questions/$uri/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsUriAnswersRoute = ApiQuestionsUriAnswersRouteImport.update({
  id: '/api/questions/$uri/answers',
  path: '/api/questions/$uri/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsUriAcceptRoute = ApiQuestionsUriAcceptRouteImport.update({
  id: '/api/questions/$uri/accept',
  path: '/api/questions/$uri/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/client-metadata.json': typeof ClientMetadataDotjsonRoute
  '/health': typeof HealthRoute
  '/jwks.json': typeof JwksDotjsonRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/me': typeof ApiMeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tags': typeof ApiTagsRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/vote': typeof ApiVoteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$handle': typeof UHandleRoute
  '/api/analytics/share': typeof ApiAnalyticsShareRoute
  '/api/analytics/view': typeof ApiAnalyticsViewRoute
  '/api/profiles/$handle': typeof ApiProfilesHandleRoute
  '/api/records/$uri': typeof ApiRecordsUriRoute
  '/q/$did/$rkey': typeof QDidRkeyRoute
  '/api/questions/': typeof ApiQuestionsIndexRoute
  '/api/questions/$uri/accept': typeof ApiQuestionsUriAcceptRoute
  '/api/questions/$uri/answers': typeof ApiQuestionsUriAnswersRoute
  '/api/questions/$uri/': typeof ApiQuestionsUriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/client-metadata.json': typeof ClientMetadataDotjsonRoute
  '/health': typeof HealthRoute
  '/jwks.json': typeof JwksDotjsonRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/me': typeof ApiMeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tags': typeof ApiTagsRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/vote': typeof ApiVoteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$handle': typeof UHandleRoute
  '/api/analytics/share': typeof ApiAnalyticsShareRoute
  '/api/analytics/view': typeof ApiAnalyticsViewRoute
  '/api/profiles/$handle': typeof ApiProfilesHandleRoute
  '/api/records/$uri': typeof ApiRecordsUriRoute
  '/q/$did/$rkey': typeof QDidRkeyRoute
  '/api/questions': typeof ApiQuestionsIndexRoute
  '/api/questions/$uri/accept': typeof ApiQuestionsUriAcceptRoute
  '/api/questions/$uri/answers': typeof ApiQuestionsUriAnswersRoute
  '/api/questions/$uri': typeof ApiQuestionsUriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/client-metadata.json': typeof ClientMetadataDotjsonRoute
  '/health': typeof HealthRoute
  '/jwks.json': typeof JwksDotjsonRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/me': typeof ApiMeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tags': typeof ApiTagsRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/vote': typeof ApiVoteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$handle': typeof UHandleRoute
  '/api/analytics/share': typeof ApiAnalyticsShareRoute
  '/api/analytics/view': typeof ApiAnalyticsViewRoute
  '/api/profiles/$handle': typeof ApiProfilesHandleRoute
  '/api/records/$uri': typeof ApiRecordsUriRoute
  '/q/$did/$rkey': typeof QDidRkeyRoute
  '/api/questions/': typeof ApiQuestionsIndexRoute
  '/api/questions/$uri/accept': typeof ApiQuestionsUriAcceptRoute
  '/api/questions/$uri/answers': typeof ApiQuestionsUriAnswersRoute
  '/api/questions/$uri/': typeof ApiQuestionsUriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/client-metadata.json'
    | '/health'
    | '/jwks.json'
    | '/login'
    | '/privacy'
    | '/search'
    | '/api/comments'
    | '/api/me'
    | '/api/search'
    | '/api/tags'
    | '/api/trending'
    | '/api/vote'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/tag/$tag'
    | '/u/$handle'
    | '/api/analytics/share'
    | '/api/analytics/view'
    | '/api/profiles/$handle'
    | '/api/records/$uri'
    | '/q/$did/$rkey'
    | '/api/questions/'
    | '/api/questions/$uri/accept'
    | '/api/questions/$uri/answers'
    | '/api/questions/$uri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/client-metadata.json'
    | '/health'
    | '/jwks.json'
    | '/login'
    | '/privacy'
    | '/search'
    | '/api/comments'
    | '/api/me'
    | '/api/search'
    | '/api/tags'
    | '/api/trending'
    | '/api/vote'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/tag/$tag'
    | '/u/$handle'
    | '/api/analytics/share'
    | '/api/analytics/view'
    | '/api/profiles/$handle'
    | '/api/records/$uri'
    | '/q/$did/$rkey'
    | '/api/questions'
    | '/api/questions/$uri/accept'
    | '/api/questions/$uri/answers'
    | '/api/questions/$uri'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/client-metadata.json'
    | '/health'
    | '/jwks.json'
    | '/login'
    | '/privacy'
    | '/search'
    | '/api/comments'
    | '/api/me'
    | '/api/search'
    | '/api/tags'
    | '/api/trending'
    | '/api/vote'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/tag/$tag'
    | '/u/$handle'
    | '/api/analytics/share'
    | '/api/analytics/view'
    | '/api/profiles/$handle'
    | '/api/records/$uri'
    | '/q/$did/$rkey'
    | '/api/questions/'
    | '/api/questions/$uri/accept'
    | '/api/questions/$uri/answers'
    | '/api/questions/$uri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ClientMetadataDotjsonRoute: typeof ClientMetadataDotjsonRoute
  HealthRoute: typeof HealthRoute
  JwksDotjsonRoute: typeof JwksDotjsonRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTagsRoute: typeof ApiTagsRoute
  ApiTrendingRoute: typeof ApiTrendingRoute
  ApiVoteRoute: typeof ApiVoteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  TagTagRoute: typeof TagTagRoute
  UHandleRoute: typeof UHandleRoute
  ApiAnalyticsShareRoute: typeof ApiAnalyticsShareRoute
  ApiAnalyticsViewRoute: typeof ApiAnalyticsViewRoute
  ApiProfilesHandleRoute: typeof ApiProfilesHandleRoute
  ApiRecordsUriRoute: typeof ApiRecordsUriRoute
  QDidRkeyRoute: typeof QDidRkeyRoute
  ApiQuestionsIndexRoute: typeof ApiQuestionsIndexRoute
  ApiQuestionsUriAcceptRoute: typeof ApiQuestionsUriAcceptRoute
  ApiQuestionsUriAnswersRoute: typeof ApiQuestionsUriAnswersRoute
  ApiQuestionsUriIndexRoute: typeof ApiQuestionsUriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwks.json': {
      id: '/jwks.json'
      path: '/jwks.json'
      fullPath: '/jwks.json'
      preLoaderRoute: typeof JwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-metadata.json': {
      id: '/client-metadata.json'
      path: '/client-metadata.json'
      fullPath: '/client-metadata.json'
      preLoaderRoute: typeof ClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote': {
      id: '/api/vote'
      path: '/api/vote'
      fullPath: '/api/vote'
      preLoaderRoute: typeof ApiVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trending': {
      id: '/api/trending'
      path: '/api/trending'
      fullPath: '/api/trending'
      preLoaderRoute: typeof ApiTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/': {
      id: '/api/questions/'
      path: '/api/questions'
      fullPath: '/api/questions/'
      preLoaderRoute: typeof ApiQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$did/$rkey': {
      id: '/q/$did/$rkey'
      path: '/q/$did/$rkey'
      fullPath: '/q/$did/$rkey'
      preLoaderRoute: typeof QDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$uri': {
      id: '/api/records/$uri'
      path: '/api/records/$uri'
      fullPath: '/api/records/$uri'
      preLoaderRoute: typeof ApiRecordsUriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/$handle': {
      id: '/api/profiles/$handle'
      path: '/api/profiles/$handle'
      fullPath: '/api/profiles/$handle'
      preLoaderRoute: typeof ApiProfilesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/view': {
      id: '/api/analytics/view'
      path: '/api/analytics/view'
      fullPath: '/api/analytics/view'
      preLoaderRoute: typeof ApiAnalyticsViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/share': {
      id: '/api/analytics/share'
      path: '/api/analytics/share'
      fullPath: '/api/analytics/share'
      preLoaderRoute: typeof ApiAnalyticsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/$uri/': {
      id: '/api/questions/$uri/'
      path: '/api/questions/$uri'
      fullPath: '/api/questions/$uri/'
      preLoaderRoute: typeof ApiQuestionsUriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/$uri/answers': {
      id: '/api/questions/$uri/answers'
      path: '/api/questions/$uri/answers'
      fullPath: '/api/questions/$uri/answers'
      preLoaderRoute: typeof ApiQuestionsUriAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/$uri/accept': {
      id: '/api/questions/$uri/accept'
      path: '/api/questions/$uri/accept'
      fullPath: '/api/questions/$uri/accept'
      preLoaderRoute: typeof ApiQuestionsUriAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ClientMetadataDotjsonRoute: ClientMetadataDotjsonRoute,
  HealthRoute: HealthRoute,
  JwksDotjsonRoute: JwksDotjsonRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiMeRoute: ApiMeRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTagsRoute: ApiTagsRoute,
  ApiTrendingRoute: ApiTrendingRoute,
  ApiVoteRoute: ApiVoteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  TagTagRoute: TagTagRoute,
  UHandleRoute: UHandleRoute,
  ApiAnalyticsShareRoute: ApiAnalyticsShareRoute,
  ApiAnalyticsViewRoute: ApiAnalyticsViewRoute,
  ApiProfilesHandleRoute: ApiProfilesHandleRoute,
  ApiRecordsUriRoute: ApiRecordsUriRoute,
  QDidRkeyRoute: QDidRkeyRoute,
  ApiQuestionsIndexRoute: ApiQuestionsIndexRoute,
  ApiQuestionsUriAcceptRoute: ApiQuestionsUriAcceptRoute,
  ApiQuestionsUriAnswersRoute: ApiQuestionsUriAnswersRoute,
  ApiQuestionsUriIndexRoute: ApiQuestionsUriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
